# periodic tests of aph

name: aph tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: dlwoodruff/mpisppyweekly:latest
        env:
          PATH: /opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


    steps:
      - uses: actions/checkout@v2
      - name: setup the program
        run: |
          python setup.py develop

      - name: run tests
        timeout-minutes: 100
        run: |
          cd mpisppy/tests
          # envall does nothing
          python test_aph.py 
